shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('tag/<slug:tag_slug>/',
         views.shop,
         name='book_list_by_tag'),
    path('<slug:author_slug>',
         views.author_detail,
         name='author_detail'),
    path('<slug:author_slug>/<slug:book_slug>/',
         views.book_detail,
         name='book_detail'),
    path('<slug:author_slug>/<slug:book_slug>/share/',
         views.book_share,
         name='book_share'),

]

shoppingsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class Genre(models.Model):
    name = models.CharField('Genre', max_length=100, help_text="Book Genre (e.g. Sci-Fi, Programming etc.")

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100, help_text="Author Name")
    f_name = models.CharField('family name', max_length=100, help_text="Author Family Name")
    slug = models.SlugField(max_length=50, help_text="Author Link")
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def __str__(self):
        return "{0} {1}".format(self.name, self.f_name)

    def auth_slug(self):
        return "{0}-{1}".format(self.name, self.f_name)


class Book(models.Model):
    title = models.CharField(max_length=150, help_text="Book Title")
    slug = models.SlugField(max_length=50, help_text="Book Link")
    description = models.TextField(max_length=1500, help_text="Book Short Description")
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, help_text="Select Author For This Book", null=True)
    genre = models.ManyToManyField(Genre, help_text="Select Genres For This Book")
    stock_available = models.IntegerField(default=5)
    img = models.ImageField(upload_to='pics', null=True, blank=True)
    item_date_published = models.DateTimeField(default=timezone.now)
    item_date_updated = models.DateTimeField(auto_now=True)
    book_date_published = models.DateField()
    tags = TaggableManager()

    def __str__(self):
        return "{0} By {1}".format(self.title, self.author)


class Comment(models.Model):
    book = models.ForeignKey(Book,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    title = models.CharField(max_length=25)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.book)

shop/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'title', 'body')

shop/views.py
from django.shortcuts import render,\
    get_object_or_404, HttpResponse

from django.views.decorators.http import require_http_methods, \
    require_safe
from .models import *
from .forms import *

import redis
from django.conf import settings

from django.core.paginator import Paginator,\
    PageNotAnInteger,\
    EmptyPage

from django.core.mail import send_mail

from taggit.models import Tag
from django.db.models import Count

from django.contrib.auth.decorators import login_required

r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)

# Create your views here.


@require_http_methods(['GET'])
def shop(request, tag_slug=None):
    items = Book.objects.order_by('item_date_updated').reverse()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        items = items.filter(tags__in=[tag])

    paginator = Paginator(items, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'page': page,
        'posts': posts,
        'tag': tag,
    }
    return render(request, 'index.html', context)


@login_required()
@require_http_methods(['GET', 'POST'])
def book_detail(request, book_slug, author_slug):
    book = get_object_or_404(Book, slug=book_slug)
    author = get_object_or_404(Author, slug=author_slug)

    comments = book.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.book = book
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    book_tags_ids = book.tags.values_list('id', flat=True)
    similar_books = Book.objects.filter(tags__in=book_tags_ids)\
        .exclude(id=book.id)
    similar_books = similar_books.annotate(same_tags=Count('tags')) \
        .order_by('-same_tags')[:4]

    context = {
        'book': book,
        'author': author,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_books': similar_books,
    }
    return render(request, 'book.html', context)


def book_share(request, book_slug, author_slug):
    book = get_object_or_404(Book, slug=book_slug)
    author = get_object_or_404(Author, slug=author_slug)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            book_url = request.build_absolute_uri()[:-6]
            subject = '{} ({}) recommends you buying "{}"'.format(cd['name'],
                                                                  cd['email'],
                                                                  book.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(book.title,
                                                                    book_url,
                                                                    cd['name'],
                                                                    cd['comments'])
            send_mail(subject, message, 'admin@shop.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'book': book,
        'form': form,
        'sent': sent,
    }
    return render(request, 'share.html', context)


@require_safe
def author_detail(request, author_slug):
    author = get_object_or_404(Author, slug=author_slug)
    context = {
        'author': author,
    }
    return render(request, 'author.html', context)

shop/templates/archive.html
{% extends 'parent/main.html' %}
{% block body %}
    <div class="list-group">
        {% for x in items %}
            <a href="{{ x.slug }}" class="list-group-item list-group-item-action">{{ x.title }}</a>
        {% endfor %}
    </div>
{% endblock %}

shop/templates/author.html
{% extends 'parent/main.html' %}
{% block body %}
{{ author.name }} {{ author.f_name }}
{% endblock %}

shop/templates/book.html
{% extends 'parent/main.html' %}
{% block body %}
	<h2>{{ book.title }}</h2>
	{% for gen in book.genre.all %}
		<span class="badge badge-warning">{{ gen }}</span>
	{% endfor %}
	{% if book.tags.all %}
		<div>
			<span class="badge badge-light">Tags:</span>
			{% for tag in book.tags.all %}
				<a href="{% url "shop:book_list_by_tag" tag.slug %}">
					<span class="badge badge-info">{{ tag.name }}</span>
				</a>
			{% endfor %}
		</div>
	{% endif %}
	{% if book.img %}
		<img class="item-img rounded img-fluid" src="{{ MEDIA_URL }}/media/{{ book.img }}">
	{% else %}
		<img class="item-img rounded img-fluid" src="{{ MEDIA_URL }}/media/pics/no_img.png" height="10%" width="10%">
	{% endif %}
	<p>{{ book.description }}</p>
	{% if book.stock_available == 0 %}
		<div class="alert alert-danger">
			<strong>Book Not Available!</strong> For More Information Contact Us.
		</div>
	{% endif %}
	<p>
		<a href="{% url "shop:book_share" author.slug book.slug %}">
			Share this post
		</a>
	</p>
	<div class="row">
		<h2 class="justify-content-center">Similar posts</h2>
		{% for book in similar_books %}
			<div class="col-sm-3">
				<p>
					<a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
				</p>
				{% if book.img %}
					<img src="{{ MEDIA_URL }}/media/{{ book.img }}" class="img-thumbnail" alt="{{ book.title }}" />
				{% else %}
					<img src="{{ MEDIA_URL }}/media/pics/no_img.png" class="img-thumbnail" alt="{{ book.title }}"  height="20%" width="20%"/>
				{% endif %}
			</div>
		{% empty %}
			There are no similar posts yet.
		{% endfor %}
	</div>
	{% include 'partials/comment.html' %}
{% endblock %}

shop/templates/index.html
{% extends 'parent/main.html' %}

{% block body %}
	<div class="row">
		{% if tag %}
			<h2>Posts tagged with "{{ tag.name }}"</h2>
		{% endif %}
		{% if posts %}
			{% for x in posts %}
				<div class="col col-sm-4 item-box">
					<h2>{{ x.title }}</h2>
					<a href="{{ x.author.slug }}"><span class="badge badge-light">By {{ x.author }}</span></a>
					{% for gen in x.genre.all %}
						<span class="badge badge-warning">{{ gen }}</span>
					{% endfor %}
					{% if x.tags.all %}
						<div>
							<span class="badge badge-light">Tags:</span>
							{% for tag in x.tags.all %}
								<a href="{% url "shop:book_list_by_tag" tag.slug %}">
									<span class="badge badge-info">{{ tag.name }}</span>
								</a>
							{% endfor %}
						</div>
					{% endif %}
					{% if x.img %}
						<img class="item-img rounded img-thumbnail img-fluid mx-auto d-block"
						     src="{{ MEDIA_URL }}/media/{{ x.img }}"
						     height="50%" width="75%">
					{% else %}
						<img class="item-img rounded img-thumbnail img-fluid mx-auto d-block"
						     src="{{ MEDIA_URL }}/media/pics/no_img.png" height="50%" width="75%">
					{% endif %}
					<p>{{ x.description|truncatechars:500 }}</p>
					{% if x.stock_available > 0 %}
						<span class="badge badge-success">Available</span>
					{% else %}
						<span class="badge badge-danger">Not Available</span>
					{% endif %}
					<a href="{{ x.author.slug }}/{{ x.slug }}"><span class="badge badge-primary">More...</span></a>
				</div>
			{% endfor %}
		{% endif %}
	</div>
	{% include 'partials/most_commented_section.html' %}
	{% include 'partials/pagination.html' with page=books %}
{% endblock %}

shop/templates/share.html
{% extends 'parent/main.html' %}

{% block body %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ book.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ book.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail"/>
        </form>
    {% endif %}
{% endblock %}